[project]
name = "djevops"
description = "Host Django without Docker"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [{name = "Michael Herrmann"}]
dependencies = ["boto3", "PyYAML==6.0.3"]
version = "0.2.12"
# When the version above changes, then `uv.lock` needs to be updated as well.
# You can do this in one of the following two ways:
# 1) Bump the version in both files with `uv version`. Eg.
#    `uv version --bump patch`
# 2) Edit the version above, then run `uv lock` to update `uv.lock` as well.
# NB: This comment must stay *below* the `version` line. `uv version` deletes
# comments placed directly above (or on) that line.

[project.scripts]
djevops = "djevops.__main__:main"

[project.urls]
Homepage = "https://github.com/mherrmann/djevops"
Repository = "https://github.com/mherrmann/djevops"

[project.optional-dependencies]
test = [
    "boto3",
    "celery==5.5.3",
    "django==5.1.2",
    "dnsimple==2.15.0",
    "hcloud==2.13.0",
    "psycopg[binary]",
    "requests==2.32.5",
    "tomli-w==1.2.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["djevops*"]

[tool.setuptools.package-data]
djevops = ["bin/*", "conf/**/*", "conf/.*", "pyproject.toml", "uv.lock"]
