[program:$SERVICE]
command=/opt/djevops/bin/with-bashrc.sh /bin/bash -c $COMMAND
directory=/srv/app
user=$USER
stdout_logfile=/var/log/$SERVICE.log
stderr_logfile=/var/log/$SERVICE.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600

; Disable log file rotation - We use logrotate for this.
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile_backups=0
