[program:worker]
command=/opt/djevops/bin/with-bashrc.sh celery -A core worker -l INFO
directory=/srv/app
user=django
stdout_logfile=/var/log/worker.log
stderr_logfile=/var/log/worker.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600

; Disable log file rotation - We use logrotate for this.
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile_backups=0
